// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type CodeExecutionResult struct {
	ID            int32
	Code          string
	Language      string
	EncodedCode   string
	Stdout        sql.NullString
	Stderr        sql.NullString
	Error         sql.NullString
	BuildDuration sql.NullFloat64
	ExecDuration  sql.NullFloat64
	CreatedAt     sql.NullTime
}
